version: '3.3'

services:
  database:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'mailserver'
      MYSQL_USER: 'mailuser'
      MYSQL_PASSWORD: 'mailuserpass'
      MYSQL_ROOT_PASSWORD: 'rootest'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d

  postfix:
    build: ./postfix
    restart: on-failure
    ports:
      - "25:25"
    volumes:
      - dovecot-sasl:/var/spool/postfix/private/dovecot
      # for fail2ban
      - /var/log/postfix/:/var/log/
    depends_on:
      - "dovecot"
      - "database"
    
  dovecot:
    build: ./dovecot
    restart: on-failure
    ports:
      - "993:993"
    volumes:
      - dovecot-sasl:/var/spool/postfix/private/dovecot
      # for fail2ban
      - /var/log/dovecot/:/var/log/
    depends_on:
      - "database"

  av:
    build: ./clamav
    restart: on-failure

      
volumes:
    dovecot-sasl: {}
    scripts: {}
