version: '3.3'

services:
  database:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'mailserver'
      MYSQL_USER: 'mailuser'
      MYSQL_PASSWORD: 'mailuserpass'
      MYSQL_ROOT_PASSWORD: 'rootest'
    expose:
      - '3306'
    volumes:
      - ./scripts/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - dockermail-mysql-db:/var/lib/mysql

  postfix:
    build: ./postfix
    restart: on-failure
    ports:
      - "25:25"
    volumes:
      - dockermail-dovecot-sasl:/var/spool/postfix/private/dovecot
      # for fail2ban
      - /var/log/postfix/:/var/log/
      # opendkim config
      - /etc/opendkim/mail:/etc/opendkim/mail
    depends_on:
      - "dovecot"
      - "database"
      - "av"
    
  dovecot:
    build: ./dovecot
    restart: on-failure
    ports:
      - "993:993"
    volumes:
      - dockermail-dovecot-sasl:/var/spool/postfix/private/dovecot
      - dockermail-maildir:/mail
      # for fail2ban
      - /var/log/dovecot/:/var/log/
    depends_on:
      - "database"

  av:
    build: ./clamav
    restart: on-failure
    expose:
      - '6666'

      
volumes:
    dockermail-dovecot-sasl: {}
    dockermail-mysql-db: {}
    dockermail-maildir: {}
